baseURL = "https://example.com"
title = 'Faceted Factlets'
description = ""
author = "Michael Deakin"
copyright = ""
languageCode = "en-us"
DefaultContentLanguage = "en-us"
enableInlineShortcodes = true
theme = 'simplog'
